import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9fafb",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "white",
  },
  headerButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1f2937",
  },
  stepIndicator: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
  },
  stepCircleActive: {
    backgroundColor: "#ee2b8c",
  },
  stepNumber: {
    fontSize: 12,
    fontWeight: "600",
    color: "#9ca3af",
  },
  stepNumberActive: {
    color: "white",
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: "#f3f4f6",
    marginHorizontal: 4,
  },
  stepLineActive: {
    backgroundColor: "#ee2b8c",
  },
  stepLabel: {
    fontSize: 12,
    color: "#9ca3af",
    marginLeft: 4,
  },
  stepLabelActive: {
    fontWeight: "600",
    color: "#1f2937",
  },
  content: {
    flex: 1,
  },
  decisionContainer: {
    padding: 16,
  },
  eventCard: {
    backgroundColor: "white",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  eventImage: {
    width: "100%",
    height: 160,
  },
  eventInfo: {
    padding: 16,
  },
  eventTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 8,
  },
  eventDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  eventDetailText: {
    fontSize: 14,
    color: "#6b7280",
  },
  hostedBy: {
    fontSize: 12,
    color: "#9ca3af",
    marginTop: 8,
  },
  subEventsSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subEventCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  subEventIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#fceaf4",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  subEventInfo: {
    flex: 1,
  },
  subEventName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1f2937",
  },
  subEventTime: {
    fontSize: 12,
    color: "#6b7280",
  },
  decisionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1f2937",
    textAlign: "center",
    marginBottom: 16,
  },
  decisionButton: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  decisionButtonDecline: {
    backgroundColor: "#fef2f2",
  },
  decisionIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#dcfce7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  decisionIconContainerDecline: {
    backgroundColor: "#fee2e2",
  },
  decisionButtonTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  decisionButtonTitleDecline: {
    color: "#dc2626",
  },
  decisionButtonSubtitle: {
    fontSize: 14,
    color: "#6b7280",
  },
  decisionButtonSubtitleDecline: {
    color: "#9ca3af",
  },
  questionsContainer: {
    padding: 16,
  },
  questionsHeader: {
    marginBottom: 24,
  },
  questionsTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  questionsSubtitle: {
    fontSize: 14,
    color: "#6b7280",
  },
  questionCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  questionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  questionText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1f2937",
    flex: 1,
  },
  requiredBadge: {
    backgroundColor: "#fef3c7",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  requiredText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#d97706",
  },
  optionsContainer: {
    gap: 8,
  },
  optionButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    backgroundColor: "#f9fafb",
  },
  optionButtonSelected: {
    borderColor: "#ee2b8c",
    backgroundColor: "#fceaf4",
  },
  optionRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  optionRadioSelected: {
    borderColor: "#ee2b8c",
  },
  optionRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ee2b8c",
  },
  optionCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  optionCheckboxSelected: {
    borderColor: "#ee2b8c",
    backgroundColor: "#ee2b8c",
  },
  optionText: {
    fontSize: 14,
    color: "#374151",
    flex: 1,
  },
  optionTextSelected: {
    fontWeight: "600",
    color: "#1f2937",
  },
  textInputContainer: {
    backgroundColor: "#f9fafb",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  textInput: {
    padding: 12,
    fontSize: 14,
    color: "#1f2937",
    minHeight: 80,
    textAlignVertical: "top",
  },
  numberInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
  },
  numberButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#fceaf4",
    alignItems: "center",
    justifyContent: "center",
  },
  numberValue: {
    fontSize: 32,
    fontWeight: "700",
    color: "#1f2937",
    minWidth: 60,
    textAlign: "center",
  },
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ee2b8c",
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  confirmationContainer: {
    padding: 24,
    alignItems: "center",
  },
  confirmationIcon: {
    marginBottom: 16,
  },
  confirmationTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1f2937",
    textAlign: "center",
    marginBottom: 8,
  },
  confirmationMessage: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    marginBottom: 24,
  },
  summaryCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    width: "100%",
    marginBottom: 24,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryContent: {
    gap: 12,
  },
  summaryItem: {
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
    paddingBottom: 8,
  },
  summaryQuestion: {
    fontSize: 12,
    color: "#9ca3af",
    marginBottom: 2,
  },
  summaryAnswer: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1f2937",
  },
  confirmationEventCard: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 16,
    overflow: "hidden",
    width: "100%",
    marginBottom: 24,
  },
  confirmationEventImage: {
    width: 80,
    height: 80,
  },
  confirmationEventInfo: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
  },
  confirmationEventTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: 2,
  },
  confirmationEventDate: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 2,
  },
  confirmationEventLocation: {
    fontSize: 12,
    color: "#9ca3af",
  },
  doneButton: {
    backgroundColor: "#ee2b8c",
    borderRadius: 12,
    padding: 16,
    width: "100%",
    alignItems: "center",
    marginBottom: 12,
  },
  doneButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "white",
  },
  addToCalendarButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
  },
  addToCalendarText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ee2b8c",
    marginLeft: 8,
  },
});
