import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f6f7",
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingTop: 40,
  },
  successHeroCircle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "#ee2b8c",
    alignSelf: "center",
    marginTop: 20,
    marginBottom: 32,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#ee2b8c",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  successHeroInner: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "#ee2b8c",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.3)",
  },
  checkmarkContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  successFloatIcon: {
    position: "absolute",
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  successFloatIcon1: {
    top: -10,
    right: -10,
  },
  successFloatIcon2: {
    bottom: 30,
    left: -20,
  },
  successFloatIcon3: {
    bottom: -5,
    right: 30,
  },
  successTextContent: {
    alignItems: "center",
    marginBottom: 32,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#181114",
    marginBottom: 12,
    textAlign: "center",
  },
  successSubtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#181114",
    marginBottom: 8,
    textAlign: "center",
  },
  successDescription: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    maxWidth: 280,
  },
  successOptions: {
    gap: 16,
    marginBottom: 32,
  },
  successOptionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  successOptionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#9333EA20",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  successOptionTextContainer: {
    flex: 1,
  },
  successOptionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#181114",
    marginBottom: 4,
  },
  successOptionSubtitle: {
    fontSize: 12,
    color: "#6B7280",
  },
  quickStats: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  quickStatsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#181114",
    marginBottom: 16,
  },
  quickStatItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
  },
  quickStatText: {
    fontSize: 14,
    color: "#6B7280",
  },
});
