import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f6f7",
  },
  keyboardAvoidingView: {
    flex: 1,
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 8,
    backgroundColor: "#f8f6f7",
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 18,
    color: "#181114",
    flex: 1,
    textAlign: "center",
  },
  headerSpacer: {
    width: 40,
  },
  progressContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  progressStep: {
    fontFamily: "PlusJakartaSans-SemiBold",
    fontSize: 12,
    color: "#6B7280",
  },
  progressLabel: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 12,
    color: "#ee2b8c",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  progressBarBackground: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "#E5E7EB",
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
    backgroundColor: "#ee2b8c",
  },
  scrollView: {
    flex: 1,
  },
  titleSection: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 16,
  },
  title: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 24,
    color: "#181114",
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 16,
    color: "#6B7280",
    lineHeight: 24,
  },
  section: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sectionTitle: {
    fontFamily: "PlusJakartaSans-SemiBold",
    fontSize: 14,
    color: "#181114",
    marginBottom: 12,
  },
  inputContainer: {
    position: "relative",
  },
  textInput: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "white",
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingRight: 48,
    fontSize: 16,
    fontFamily: "PlusJakartaSans-Medium",
    color: "#181114",
  },
  inputIcon: {
    position: "absolute",
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: "center",
  },
  budgetRow: {
    flexDirection: "row",
    gap: 12,
  },
  budgetInput: {
    flex: 2,
  },
  currencyIcon: {
    position: "absolute",
    left: 16,
    top: 0,
    bottom: 0,
    justifyContent: "center",
  },
  currencySymbol: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#6B7280",
  },
  currencyScroll: {
    flex: 1,
  },
  currencyButton: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "white",
    marginRight: 8,
  },
  currencyButtonSelected: {
    backgroundColor: "#ee2b8c",
    borderColor: "#ee2b8c",
  },
  currencyText: {
    fontFamily: "PlusJakartaSans-SemiBold",
    fontSize: 14,
    color: "#6B7280",
  },
  currencyTextSelected: {
    color: "white",
  },
  privacySection: {
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  privacyContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "rgba(238, 43, 140, 0.1)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(238, 43, 140, 0.2)",
  },
  privacyTextContainer: {
    flex: 1,
    paddingRight: 16,
  },
  privacyTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 14,
    color: "#181114",
    marginBottom: 4,
  },
  privacySubtitle: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 12,
    color: "#6B7280",
  },
  tipContainer: {
    flexDirection: "row",
    gap: 12,
    marginHorizontal: 16,
    marginTop: 32,
    padding: 16,
    backgroundColor: "#F9FAFB",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tipText: {
    flex: 1,
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 12,
    color: "#6B7280",
    fontStyle: "italic",
    lineHeight: 18,
  },
  bottomSpacing: {
    height: 140,
  },
  footer: {
    flexDirection: "row",
    gap: 12,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: 32,
    backgroundColor: "#f8f6f7",
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
  },
  backButton: {
    flex: 1,
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  backButtonText: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#6B7280",
  },
  nextButton: {
    flex: 2,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#ee2b8c",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#ee2b8c",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  nextButtonText: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "white",
  },
});
