import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f6f7",
    maxWidth: 480,
    alignSelf: "center",
    width: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 8,
    backgroundColor: "white",
  },
  closeButton: {
    width: 48,
    height: 48,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 18,
    color: "#181114",
    flex: 1,
    textAlign: "center",
    paddingRight: 48,
  },
  headerSpacer: {
    width: 48,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  heroContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 32,
  },
  heroCircle: {
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "rgba(238, 43, 140, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  heroInner: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 4,
    borderColor: "white",
    overflow: "hidden",
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  floatIcon: {
    position: "absolute",
    padding: 12,
    backgroundColor: "white",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  floatIcon1: {
    top: 20,
    left: 20,
  },
  floatIcon2: {
    bottom: 30,
    right: 20,
  },
  floatIcon3: {
    top: 40,
    right: 15,
  },
  textContent: {
    alignItems: "center",
    marginBottom: 32,
  },
  title: {
    fontFamily: "PlusJakartaSans-Extrabold",
    fontSize: 28,
    color: "#181114",
    textAlign: "center",
    lineHeight: 36,
  },
  subtitle: {
    fontFamily: "PlusJakartaSans-Medium",
    fontSize: 16,
    color: "#635c60",
    textAlign: "center",
    lineHeight: 24,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  optionButtons: {
    width: "100%",
    gap: 16,
  },
  optionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    padding: 16,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  optionIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#FAF5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  optionTextContainer: {
    flex: 1,
  },
  optionTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#181114",
  },
  optionSubtitle: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  sectionTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 20,
    color: "#181114",
    marginBottom: 16,
  },
  eventsList: {
    gap: 12,
    paddingBottom: 24,
  },
  eventCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  eventImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
  },
  eventInfo: {
    flex: 1,
  },
  eventName: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#181114",
  },
  eventDate: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  eventSubEvents: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  eventSubEventsText: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 12,
    color: "#9CA3AF",
  },
  subEventHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  subEventTitle: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 18,
    color: "#181114",
    flex: 1,
  },
  addSubEventButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
    backgroundColor: "rgba(238, 43, 140, 0.1)",
    borderRadius: 16,
    marginBottom: 16,
  },
  addSubEventText: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#ee2b8c",
  },
  subEventsList: {
    flex: 1,
  },
  subEventCard: {
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 12,
    overflow: "hidden",
  },
  subEventInfo: {
    padding: 16,
  },
  subEventName: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 16,
    color: "#181114",
  },
  subEventVendorCount: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
  },
  subEventDetails: {
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    padding: 16,
  },
  vendorItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  vendorInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  vendorName: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 14,
    color: "#181114",
  },
  vendorStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusBooked: {
    backgroundColor: "#DCFCE7",
  },
  statusPending: {
    backgroundColor: "#FEF3C7",
  },
  vendorStatusText: {
    fontFamily: "PlusJakartaSans-Medium",
    fontSize: 12,
  },
  statusBookedText: {
    color: "#15803D",
  },
  statusPendingText: {
    color: "#D97706",
  },
  noVendorsText: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 14,
    color: "#9CA3AF",
    textAlign: "center",
    paddingVertical: 8,
  },
  addVendorButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#EE2B8C",
    borderRadius: 12,
    borderStyle: "dashed",
  },
  addVendorText: {
    fontFamily: "PlusJakartaSans-Medium",
    fontSize: 14,
    color: "#ee2b8c",
  },
  emptySubEvents: {
    alignItems: "center",
    paddingVertical: 48,
  },
  emptySubEventsText: {
    fontFamily: "PlusJakartaSans-Bold",
    fontSize: 18,
    color: "#181114",
    marginTop: 16,
  },
  emptySubEventsSubText: {
    fontFamily: "PlusJakartaSans-Regular",
    fontSize: 14,
    color: "#6B7280",
    marginTop: 4,
  },
});
