// Sample data - In production, this would come from the API

import { useGuests, type Guest } from "@/src/features/guests/hooks/useGuests";
export const SAMPLE_GUESTS: Guest[] = [
  {
    id: "1",
    name: "Priya Sharma",
    initials: "PS",
    avatar: "https://example.com/avatar1.jpg",
    relation: "Friend",
    phone: "+91 98765 43210",
    dietaryRestrictions: ["Vegetarian"],
    hasPlusOne: true,
    plusOneName: "Amit",
    status: "Going",
    category: "Groom's Colleague",
    source: "manual",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Rahul Kapoor",
    initials: "RK",
    relation: "Family",
    phone: "+91 98765 43211",
    hasPlusOne: false,
    status: "Going",
    category: "Bride's Family",
    source: "manual",
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    name: "Sarah Jenkins",
    initials: "SJ",
    relation: "Friend",
    phone: "+91 98765 43212",
    hasPlusOne: true,
    status: "Pending",
    category: "Groom's Friend",
    source: "excel",
    createdAt: "2024-01-08",
  },
  {
    id: "4",
    name: "Mike Johnson",
    initials: "MJ",
    relation: "Colleague",
    phone: "+91 98765 43213",
    dietaryRestrictions: ["Vegan", "Gluten-Free"],
    hasPlusOne: false,
    status: "Not Going",
    category: "Work",
    source: "manual",
    createdAt: "2024-01-05",
  },
  {
    id: "5",
    name: "Emily Davis",
    initials: "ED",
    relation: "Neighbor",
    hasPlusOne: false,
    status: "Not Invited",
    source: "contact",
  },
  {
    id: "6",
    name: "John Smith",
    initials: "JS",
    relation: "Relative",
    phone: "+91 98765 43214",
    hasPlusOne: true,
    plusOneName: "Jane",
    status: "Going",
    category: "Groom's Family",
    source: "manual",
    createdAt: "2024-01-12",
  },
  {
    id: "7",
    name: "Lisa Anderson",
    initials: "LA",
    relation: "Friend",
    phone: "+91 98765 43215",
    hasPlusOne: false,
    status: "Pending",
    source: "excel",
    createdAt: "2024-01-14",
  },
  {
    id: "8",
    name: "David Wilson",
    initials: "DW",
    relation: "Colleague",
    hasPlusOne: true,
    plusOneName: "Sarah",
    status: "Not Invited",
    category: "Work",
    source: "manual",
  },
];
