import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Table Card Styles
  tableCard: {
    position: "absolute",
    backgroundColor: "white",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  tableCardCircle: {
    borderRadius: 80,
    width: 160,
    height: 160,
    alignItems: "center",
    justifyContent: "center",
  },
  tableCardSelected: {
    borderColor: "#ee2b8c",
    borderWidth: 2,
  },
  rectangleSeats: {
    padding: 8,
  },
  rectangleSeatTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  rectangleSeatBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rectangleSeatBox: {
    width: 40,
    height: 24,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  seatEmpty: {
    borderColor: "#e5e7eb",
    backgroundColor: "#f9fafb",
  },
  seatFilled: {
    backgroundColor: "#10B981",
    borderColor: "#10B981",
  },
  seatGuestLabel: {
    fontSize: 8,
    fontWeight: "600",
    color: "white",
  },
  seatNumberLabel: {
    fontSize: 8,
    color: "#9CA3AF",
  },
  circleTable: {
    alignItems: "center",
  },
  tableLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#ee2b8c",
    letterSpacing: 1,
  },
  tableNumber: {
    fontSize: 28,
    fontWeight: "700",
    color: "#374151",
  },
  circleGuests: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 8,
    paddingHorizontal: 16,
  },
  circleGuestDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#8B5CF6",
    alignItems: "center",
    justifyContent: "center",
    margin: 2,
  },
  circleGuestInitial: {
    fontSize: 10,
    fontWeight: "700",
    color: "white",
  },
  moreGuests: {
    fontSize: 10,
    color: "#6B7280",
    marginLeft: 4,
  },
  occupancyBadge: {
    position: "absolute",
    bottom: -12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  occupancyText: {
    fontSize: 10,
    fontWeight: "700",
    color: "white",
  },
  selectedRing: {
    position: "absolute",
    inset: -4,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#ee2b8c",
    borderStyle: "dashed",
  },
  // Group Chip Styles
  groupChip: {
    backgroundColor: "#f8f6f6",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 120,
  },
  groupChipSelected: {
    borderColor: "#ee2b8c",
    backgroundColor: "#ee2b8c10",
  },
  groupChipHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  groupChipName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#374151",
  },
  groupChipBadge: {
    backgroundColor: "#ee2b8c",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  groupChipBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "white",
  },
  groupChipMembers: {
    fontSize: 10,
    color: "#6B7280",
  },
  // Floor Plan Styles
  canvasContainer: {
    flex: 1,
    position: "relative",
  },
  canvasGrid: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    padding: 32,
    paddingTop: 64,
  },
  canvasInfo: {
    position: "absolute",
    bottom: 24,
    left: 24,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ee2b8c10",
  },
  guestAvatars: {
    flexDirection: "row",
    marginRight: 12,
  },
  avatarDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#f3f4f6",
    borderWidth: 2,
    borderColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -8,
  },
  avatarText: {
    fontSize: 8,
    fontWeight: "700",
    color: "#6B7280",
  },
  canvasInfoText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#374151",
  },
  floatingControls: {
    position: "absolute",
    bottom: 24,
    right: 24,
    flexDirection: "column",
    gap: 12,
  },
  fab: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  fabAdd: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#ee2b8c",
    shadowColor: "#ee2b8c",
    shadowOpacity: 0.3,
  },
  // Drawer Styles
  drawer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  drawerHandle: {
    width: 48,
    height: 4,
    backgroundColor: "#e5e7eb",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
  },
  drawerContent: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 24,
  },
  drawerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
  },
  drawerSubtitle: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  editButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#ee2b8c10",
    alignItems: "center",
    justifyContent: "center",
  },
  seatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  seatSlot: {
    width: "47%",
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f8f6f6",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#ee2b8c20",
    borderStyle: "dashed",
  },
  seatSlotFilled: {
    backgroundColor: "white",
    borderStyle: "solid",
    borderColor: "#10B981",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  seatSlotGroup: {
    borderColor: "#8B5CF6",
  },
  seatNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  seatNumberFilled: {
    backgroundColor: "#10B981",
  },
  seatNumberGroup: {
    backgroundColor: "#8B5CF6",
  },
  seatNumberText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  seatNumberTextFilled: {
    color: "white",
  },
  seatGuestInfo: {
    flex: 1,
  },
  seatGuestName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
  },
  seatGroupLabel: {
    fontSize: 10,
    color: "#8B5CF6",
    fontWeight: "600",
  },
  seatEmptyText: {
    flex: 1,
    fontSize: 14,
    color: "#9CA3AF",
  },
  // Modal Styles
  modalOverlay: {
    position: "absolute",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    maxHeight: "70%",
  },
  modalHandle: {
    width: 48,
    height: 4,
    backgroundColor: "#e5e7eb",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 16,
  },
  groupList: {
    maxHeight: 300,
  },
  groupOption: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#f8f6f6",
    borderRadius: 12,
    marginBottom: 8,
  },
  groupOptionDisabled: {
    opacity: 0.5,
  },
  groupOptionInfo: {
    flex: 1,
  },
  groupOptionName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2937",
  },
  groupOptionMembers: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  groupOptionSize: {
    fontSize: 11,
    color: "#9CA3AF",
    marginTop: 4,
  },
  groupOptionCheck: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  groupOptionCheckActive: {
    backgroundColor: "#10B981",
  },
  tableOptions: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
  },
  tableOption: {
    flex: 1,
    alignItems: "center",
    padding: 20,
    backgroundColor: "#f8f6f6",
    borderRadius: 16,
  },
  tableOptionName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginTop: 8,
  },
  tableOptionCapacity: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  modalClose: {
    alignItems: "center",
    paddingVertical: 16,
  },
  modalCloseText: {
    fontSize: 16,
    color: "#6B7280",
  },
});
